export const apiKey = '3886d65df3b1479cb8f195300243011'; // from https://www.weatherapi.com



export const weatherImages = {
    'Partly cloudy': require('../assets/images/partlycloudy.png'),
    'Moderate rain': require('../assets/images/moderaterain.png'),
    'Patchy rain possible': require('../assets/images/moderaterain.png'),
    'Patchy rain nearby': require('../assets/images/moderaterain.png'),
    'Sunny': require('../assets/images/sun.png'),
    'Clear': require('../assets/images/sun.png'),
    'Overcast': require('../assets/images/cloud.png'),
    'Cloudy': require('../assets/images/cloud.png'),
    'Light rain': require('../assets/images/moderaterain.png'),
    'Moderate rain at times': require('../assets/images/moderaterain.png'),
    'Heavy rain': require('../assets/images/heavyrain.png'),
    'Heavy rain at times': require('../assets/images/heavyrain.png'),
    'Moderate or heavy freezing rain': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain shower': require('../assets/images/heavyrain.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/heavyrain.png'),
    'Mist': require('../assets/images/mist.png'),
    'Fog': require('../assets/images/mist.png'),
    'Snow' : require('../assets/images/snow.png'),
    'Light snow' : require('../assets/images/snow.png'),
    'Moderate snow' : require('../assets/images/snow.png'),
    'Heavy snow' : require('../assets/images/snow.png'),
    'Light drizzle' : require('../assets/images/moderaterain.png'),
    'Moderate drizzle' : require('../assets/images/moderaterain.png'),
    'Heavy drizzle' : require('../assets/images/moderaterain.png'),
    'Light freezing rain' : require('../assets/images/heavyrain.png'),
    'Moderate freezing rain' : require('../assets/images/heavyrain.png'),
    'Heavy freezing rain' : require('../assets/images/heavyrain.png'),
    'Light sleet' : require('../assets/images/heavyrain.png'),
    'Moderate sleet' : require('../assets/images/heavyrain.png'),
    'Heavy sleet' : require('../assets/images/heavyrain.png'),
    'Light rain shower' : require('../assets/images/moderaterain.png'),
    'Moderate rain shower' : require('../assets/images/moderaterain.png'),
    'Heavy rain shower' : require('../assets/images/heavyrain.png'),
    'Light snow shower' : require('../assets/images/snow.png'),
    'Moderate snow shower' : require('../assets/images/snow.png'),
    'Heavy snow shower' : require('../assets/images/snow.png'),
    'Light sleet shower' : require('../assets/images/heavyrain.png'),
    'Moderate sleet shower' : require('../assets/images/heavyrain.png'),
    'Heavy sleet shower' : require('../assets/images/heavyrain.png'),
    'Light freezing drizzle' : require('../assets/images/heavyrain.png'),
    'Moderate freezing drizzle' : require('../assets/images/heavyrain.png'),
    'other': require('../assets/images/moderaterain.png')

}